// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    ElButton: typeof import('element-plus/es')['ElButton']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElPopover: typeof import('element-plus/es')['ElPopover']
    ElStep: typeof import('element-plus/es')['ElStep']
    ElSteps: typeof import('element-plus/es')['ElSteps']
    Flower: typeof import('./src/components/Icons/Flower.vue')['default']
    Item: typeof import('./src/components/Item/Item.vue')['default']
    MySite: typeof import('./src/components/MySite/MySite.vue')['default']
    Nav: typeof import('./src/components/Nav/Nav.vue')['default']
    New: typeof import('./src/components/New/New.vue')['default']
    Sites: typeof import('./src/components/Sites/Sites.vue')['default']
  }
}

export { }
